//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManagement.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.DeliveryNotes = new HashSet<DeliveryNote>();
        }
    
        public System.Guid Bookcode { get; set; }
        public string BookName { get; set; }
        public Nullable<System.Guid> BookGenrecode { get; set; }
        public Nullable<System.Guid> Suppliercode { get; set; }
        public Nullable<System.Guid> Authorcode { get; set; }
        public Nullable<System.Guid> BookPublishercode { get; set; }
        public Nullable<int> Quanity { get; set; }
        public Nullable<int> YearOfPublication { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Author Author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryNote> DeliveryNotes { get; set; }
        public virtual BookGenre BookGenre { get; set; }
        public virtual BookPublisher BookPublisher { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
