//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManagement.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryNote
    {
        public System.Guid DeliveryNotecode { get; set; }
        public Nullable<System.Guid> Employeecode { get; set; }
        public Nullable<System.Guid> Bookcode { get; set; }
        public Nullable<int> Quanity { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
