//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManagement.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRole
    {
        public System.Guid EmployeeRolecode { get; set; }
        public string EmployeeRoleName { get; set; }
        public Nullable<System.Guid> Employeecode { get; set; }
        public Nullable<bool> EmployeeStatus { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
